redis-cluster:
  usePassword: false
  service:
    # Supported types are 'ClusterID' and 'LoadBalancer'
    type: ClusterIP
  cluster:
    nodes: 3 # defaults to 6
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain # default is 'Retain'
    whenDeleted: Delete # default is 'Retain'
