redis-cluster:
  usePassword: false
  cluster:
    nodes: 6 # 6 for redundancy. 6 'nodes' & 1 'replicas' gives 3 masters and 3 replicas in total
    replicas: 1 # 1 replica per master node
    externalAccess:
      enabled: false
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain # default is 'Retain'
    whenDeleted: Delete # default is 'Retain'
  persistence:
    enabled: true
  redis:
    podLabels:
      tags.datadoghq.com/service: redis-cluster
    affinity: {}
    topologySpreadConstraints: []
