redis-cluster:
  usePassword: false
  cluster:
    nodes: 3 # defaults to 6, minimum required is 3.
    replicas: 1 # 1 replica per master node
    externalAccess:
      enabled: false
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain # default is 'Retain'
    whenDeleted: Delete # default is 'Retain'
  redis:
    topologySpreadConstraints: []
