{{- if and .Values (index .Values "datadog-operator") (index .Values "datadog-operator" "enabled") }}
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  labels:
    {{- include "datadog-operator.labels" . | nindent 4 }}
spec:
  global:
    clusterName: {{ .Values.datadogAgent.clusterName }}
    site: {{ .Values.datadogAgent.site | default "datadoghq.eu" }}
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    {{- with .Values.datadogAgent.global }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  features:
    {{- .Values.datadogAgent.features | toYaml | nindent 4 }}
  {{- with .Values.datadogAgent.override }}
  override:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
