descheduler:
  enabled: true

  kind: Deployment
  deschedulingInterval: 5m

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

  podLabels:
    tags.datadoghq.com/service: descheduler

  deschedulerPolicy:
    maxNoOfPodsToEvictPerNode: 5
    maxNoOfPodsToEvictPerNamespace: 10

    profiles:
      - name: default
        pluginConfig:
          - name: "DefaultEvictor"
            args:
              ignorePvcPods: false
              evictLocalStoragePods: false
              minReplicas: 2

          - name: RemoveDuplicates
          - name: RemovePodsHavingTooManyRestarts
          - name: RemovePodsViolatingNodeTaints
          - name: RemovePodsViolatingNodeAffinity
          - name: LowNodeUtilization
          - name: RemovePodsViolatingPodAffinity
          - name: RemovePodsViolatingInterPodAffinity
          - name: RemovePodsViolatingTopologySpreadConstraint
            args:
              constraints:
                - DoNotSchedule
                - ScheduleAnyway

        plugins:
          balance:
            enabled:
              #- RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
              #- LowNodeUtilization
          deschedule:
            enabled:
              #- RemovePodsHavingTooManyRestarts
              #- RemovePodsViolatingNodeTaints
              #- RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity
