aws-ebs-csi-driver:
  # Use the provisioner cluster role as a workaround to patch the gp2 storageClass in the init container
  sidecars:
    provisioner:
      additionalClusterRoleRules:
        - apiGroups: ["storage.k8s.io"]
          resources: ["storageclasses"]
          verbs: ["patch"]

  # Storage Classes to be created. Notes:
  # - All storage classes are being set to be Deleted when no longer in use.
  # - No volumes will be created until there is a pod that needs it.
  storageClasses:
    - name: ebs-gp3
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      labels: {}
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        encrypted: "false"
        type: "gp3"
        tagSpecification_1: "Name={{ .PVCNamespace }}/{{ .PVCName }}"
        tagSpecification_2: "namespace={{ .PVCNamespace }}"
        tagSpecification_3: "pvcname={{ .PVCName }}"
        tagSpecification_4: "pvname={{ .PVName }}"
    - name: ebs-io2
      annotations: {}
      labels: {}
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        encrypted: "false"
        type: "io2"
        tagSpecification_1: "Name={{ .PVCNamespace }}/{{ .PVCName }}"
        tagSpecification_2: "namespace={{ .PVCNamespace }}"
        tagSpecification_3: "pvcname={{ .PVCName }}"
        tagSpecification_4: "pvname={{ .PVName }}"

  controller:
    podLabels:
      tags.datadoghq.com/service: aws-ebs-csi-driver
    initContainers:
      - name: disable-default-sc-gp2
        image: bitnami/kubectl:latest
        command: ["kubectl", "patch", "storageclass", "gp2", "-p", '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}']

    # Enable volume modification via annotations for ebs volumes.
    volumeModificationFeature:
      enabled: true

    # EKS Cluster Name
    k8sTagClusterId:

    serviceAccount:
      name: ebs-csi-controller-sa
      annotations:
        eks.amazonaws.com/role-arn:

    region:
