{{- $fullName := include "cert-manager-issuers.fullname" . -}}
{{- $labels := include "cert-manager-issuers.labels" . -}}
{{- range .Values.clusterIssuers }}
{{- if (dig "enabled" true .) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}-issuer
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- range $key, $val := . }}
  {{- if not (has $key (list "enabled" "namespace" "name")) }}
  {{- if or (kindIs "map" $val) }}
  {{ $key }}:
    {{- $val | toYaml | nindent 4}}
  {{- else }}
  {{ $key }}: {{ $val }}
  {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
