kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
data:
  hooks.yaml: |
    {{- range $key, $val := .Values.hooks }}
    - {{ $val.hook | toYaml | indent 6 | trim }}
    {{- end }}
  {{- range $key, $hook := .Values.hooks }}
  {{- range $name, $val := $hook.files }}
  {{- if $hook.enabled }}
  file_{{ $name | replace "/" "_" | replace "%" "." }}: |
    {{- $val | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
