{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.kind | default "Role" }}
metadata:
  name: {{ include "webhook.serviceAccountName" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}
