{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.kind | default "Role" }}Binding
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.kind }}
  name: {{ .Values.rbac.existingRole | default (include "webhook.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
