{{- if and .Values.ingressroute.enabled .Values.ingressroute.tls.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "webhook.fullname" . }}-redirect-https
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
