postgresql:
  serviceAccount:
    create: true

  architecture: standalone

  auth:
    enablePostgresUser: true
    postgresPassword: ""

    database: ""

    username: ""
    password: ""

    #existingSecret: postgresql-secret

  primary:
    name: master

    podLabels:
      tags.datadoghq.com/service: postgresql

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
    #  limits:
    #    memory: 512Mi
    #    cpu: 500m

    persistence:
      size: 8Gi

    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete # default is 'Retain'

