# Warning: This chart is primarily used for development, so we don't retain the PVCs by default. RDS is recommended for production.
postgresql:
  serviceAccount:
    create: true

  useDeployment: true

  settings:
    initDbArgs: ""

    superuser:
      value: "postgres"

    superuserPassword:
      value: ""

    # Use an existing secret for superuser credentials instead of static values
    # existingSecret: "postgresql-secret"
    # superuser:
    #   secretKey: "superuserUsername"
    # superuserPassword:
    #   secretKey: "superuserPassword"

  userDatabase:
    # Create a user database on startup
    name:
      value: "temp"

    # Create a user with access to the database
    user:
      value: ""
    password:
      value: ""

    # Use an existing secret for credentials instead of static values
    # existingSecret: "mysql-secret"
    # name:
    #   secretKey: "database"
    # user:
    #   secretKey: "user"
    # password:
    #   secretKey: "password"

  podLabels:
    tags.datadoghq.com/service: postgresql

  priorityClassName: ""
  nodeSelector: {}
  tolerations: []

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    # limits:
    #   memory: 512Mi
    #   cpu: 500m

  storage:
    volumeName: "postgresql-data"
    requestedSize: 8Gi
    keepPVC: false

  networkPolicy: {}
  customScripts: {} # custom scripts to run on startup (.sh, .sql files that will be placed in /docker-entrypoint-initdb.d)
  extraScripts: "" # configmap that contains custom scripts to run on startup
  #extraConfigs: []

  # Custom configuration that will be mounted in /etc/postgresql/postgresql.conf
  customConfig: |
  #   # Custom config
  #   ...
