apiVersion: v2
name: datadog-operator
description: A Helm chart for Datadog Operator with a configurable DatadogAgent deployment

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: datadog-operator
    version: 1.5.1
    repository: https://helm.datadoghq.com
    condition: datadog-operator.enabled
  - name: secrets
    repository: file://../secrets
    version: 0.1.0
    condition: secrets.secrets
