datadog-operator:
  enabled: true
  installCRDs: true

  podLabels:
    tags.datadoghq.com/service: datadog-operator

  # Intake site
  site: datadoghq.eu

  # Datadog credentials secret name
  appKeyExistingSecret: datadog-secret
  apiKeyExistingSecret: datadog-secret

  watchNamespaces:
    - datadog
    - monitoring

secrets:
  secrets:
    # Your DataDog credentials - Application Key & API Key
    # Note: If you update these, you will need to restart the deployments, as the secret is not automatically reloaded.
    datadog-secret:
      # Generate an Application Key here: https://app.datadoghq.eu/organization-settings/application-keys
      app-key:
      # Generate an API Key here: https://app.datadoghq.eu/organization-settings/api-keys
      api-key:


datadogAgent:
  clusterName:
  site: datadoghq.eu

  # Configuration options available here:
  # https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md
  global: {}
  override:
    nodeAgent:
      priorityClassName: "system-node-critical"
      # Allow to schedule on tainted nodes
      tolerations:
        - operator: Exists
      # Do not try to schedule on fargate nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
  features:
    #admissionController:
    #  enabled: true
    apm:
      enabled: true
    #clusterChecks:
    #  enabled: true
    #cspm:
    #  enabled: false
    #cws:
    #  enabled: false
    #ebpfCheck:
    #  enabled: false
    #externalMetricsServer:
    #  enabled: false
    #kubeStateMetricsCore:
    #  enabled: true
    #liveContainerCollection:
    #  enabled: true
    liveProcessCollection:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    npm:
      enabled: false
    #oomKill:
    #  enabled: false
    #orchestratorExplorer:
    #  enabled: true
    #prometheusScrape:
    #  enabled: false
    #tcpQueueLength:
    #  enabled: false
    #usm:
    #  enabled: false

