apiVersion: v2
name: harbor-container-webhook
description: A Helm chart for Harbor Mutating Webhook that rewrites container images

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: harbor-container-webhook
    version: 0.8.1
    repository: https://indeedeng.github.io/harbor-container-webhook/
    condition: harbor-container-webhook.enabled
