apiVersion: v2
name: smb-csi-driver
description: A Helm chart for SMB CSI Driver

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: csi-driver-smb
    version: v1.14.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
