aws-load-balancer-controller:
  serviceAccount:
    create: true
    name: aws-load-balancer-controller

  # Specify required details about the EKS environment, by specifying all, it works to run the controller on Fargate.
  clusterName:
  region:
  vpcId:
