aws-load-balancer-controller:
  # Enable volume modification via annotations for ebs volumes.
  controller:
    volumeModificationFeature:
      enabled: true

  serviceAccount:
    # Override the name, as terraform will usually set the irsa to only allow 'kube-system:aws-load-balancer-controller' in the trust policy.
    name: aws-load-balancer-controller
    annotations:
      # AWS Load Balancer Controller IAM role for service account (IRSA)
      eks.amazonaws.com/role-arn:

  # Specify details about the EKS environment, if all is provided it will also run on Fargate.
  clusterName:
  region:
  vpcId:
