{{- $labels := include "secrets.labels" . -}}
{{- range $secretName, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  {{- if .namespaceOverride }}
  namespace: {{ .namespaceOverride }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
    {{- if and $values.labels (kindIs "map" $values.labels) }}
    {{- toYaml $values.labels | nindent 4 }}
    {{- end }}
  {{- if and $values.annotations (kindIs "map" $values.annotations) }}
  annotations:
    {{- toYaml $values.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := $values }}
  {{- if and (ne $key "namespaceOverride") (not (and (eq $key "labels") (kindIs "map" $value))) (not (and (eq $key "annotations") (kindIs "map" $value))) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
