{{- $labels := include "secrets.labels" . -}}
{{- range $secretName, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  {{- if .namespaceOverride }}
  namespace: {{ .namespaceOverride }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $values }}
  {{- if ne $key "namespaceOverride" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
