aws-efs-csi-driver:
  controller:
    deleteAccessPointRootDir: true
    tags: {}
    serviceAccount:
      create: true
      name: efs-csi-controller-sa
      annotations:
        eks.amazonaws.com/role-arn:
  node:
    serviceAccount:
      create: true
      name: efs-csi-node-sa
      annotations:
        eks.amazonaws.com/role-arn:

  storageClasses: []
    #- name: efs-tmp
    #  reclaimPolicy: Delete
    #  volumeBindingMode: WaitForFirstConsumer
    #  parameters:
    #    provisioningMode: efs-ap
    #    fileSystemId: fs-06827e90c60c3461d
    #    directoryPerms: "700"
    #    # Optional parameters
    #    uid: "1000"
    #    gid: "1000"
    #    basePath: "/dynamic"
    #    subPathPattern: "/${.PVC.namespace}/${.PVC.name}"
    #    ensureUniqueDirectory: "false" # Be careful when 'false', see warning in the official aws-efs-csi-drive docs.
    #    reuseAccessPoint: "true"
