tailscale-operator:
  # Create an OAuth client in the admin console, with the following permissions:
  # - 'Devices -> Core' write scope and the tag 'tag:k8s-operator'
  # - 'Keys -> Auth Keys' write scope and the tag 'tag:k8s-operator'
  oauth:
    clientId: ""
    clientSecret: ""

  operatorConfig:
    podLabels:
      tags.datadoghq.com/service: tailscale-operator
