prometheus:
  server:
    podLabels:
      tags.datadoghq.com/service: prometheus

    retention: 1h

    resources:
      requests:
        cpu: 500m
        memory: 512Mi

    global:
      scrape_interval: 15s
