aws-s3-csi-driver:
  node:
    serviceAccount:
      create: true
      name: s3-csi-driver-sa
      annotations:
        # Specify the SA's role ARN if running in EKS. Otherwise, the driver will be "Forbidden" from accessing s3 buckets
        eks.amazonaws.com/role-arn:
