microservice:
  replicaCount: 1

  nameOverride: "speedtest"

  image:
    repository: openspeedtest/latest
    tag: "latest"

  datadog:
    enabled: true

  imagePullSecrets: []

  service:
    port: 3000

  ingressroute:
    responseHeaderMicroservice: true
    tls:
      forceHttps: false
    routes:
      - path: /speedtest
        priority: 910
        stripPrefix: /speedtest
        redirect:
          regex: ^(https?://[a-z0-9-.]+)/speedtest$
          replacement: $1/speedtest/
        middlewares:
          buffering:
            maxRequestBodyBytes: 10000000000
            memRequestBodyBytes: 10000000000
            memResponseBodyBytes: 10000000000
            maxResponseBodyBytes: 10000000000

  probes:
    livenessPath: /
    readinessPath: /
