microservice:
  image:
    repository: openspeedtest/latest
    tag: "latest"

  imagePullSecrets: []

  service:
    port: 3000

  ingressroute:
    responseHeaderMicroservice: true
    routes:
      - path: /speedtest
        priority: 910
        stripPrefix: /speedtest

  probes:
    livenessPath: /
    readinessPath: /
