traefik:
  image:
    tag:

  rbac:
    enabled: true

  ingressRoute:
    healthcheck:
      enabled: true
      entryPoints:
        - web
        - websecure
  # Enable dashboard - don't keep it publicly open on production environments without appropriate protection (fw, security groups, auth, ip filtering, etc.)
    dashboard:
      enabled: true

  # -- You SHOULD NOT expose the traefik port on production deployments.
  ports:
    traefik:
      expose:
        default: true

    websecure:
      tls: {}

  # Enable access logs
  logs:
    general:
      # Format is required due to a bug in the helm chart for the specific version K3s is using at the time being (2023-09).
      format: common
      # Set the debug level to debug temporarily to troubleshoot
      #level: DEBUG
    access:
      enabled: true

  service:
    annotations:
      # On AWS, create a Network load balancer with IP target groups
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true

      # You must specify three elastic IPs if you are using 3 availability zones and 3 subnets
      #service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-xxx, eipalloc-yyy, eipalloc-zzz

  externalTrafficPolicy: Local

  persistence:
    enabled: false

  providers:
    kubernetesCRD:
      # Allow the IngressRoute to create an empty servers load balancer if the targeted Kubernetes service has no endpoints available
      allowEmptyServices: false
      # Allow the IngressRoute to reference an externalName Service
      allowExternalNameServices: false
      # Allow the IngressRoute to reference a Service in a different namespace
      allowCrossNamespace: false

  ## Use an existing tls cert and set as default, for example when you use cert-manager for certificate management
  #tlsStore:
  #  default:
  #    defaultCertificate:
  #      secretName: wildcard-example-com-tls

  #
  # High Availability Configuration below
  #

  deployment:
    replicas: 3
    labels:
      tags.datadoghq.com/service: traefik
    podLabels:
      tags.datadoghq.com/service: traefik

  priorityClassName: "system-cluster-critical"

  topologySpreadConstraints:
    # This example topologySpreadConstraints forces the scheduler to put traefik pods on nodes where no other traefik pods are scheduled.
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Release.Namespace }}'
      matchLabelKeys:
        - pod-template-hash
    - maxSkew: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Release.Namespace }}'
      matchLabelKeys:
        - pod-template-hash

  # Termination grace period should be set higher than the "grace period" of the LB you are using
  terminationGracePeriodSeconds: 60

  # Recycle pods one by one
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  # Enable the experimental plugins
  experimental:
    plugins: {}
      # traefik-api-key-auth:
      #   moduleName: github.com/JimCronqvist/traefik-api-key-auth
      #   version: v0.0.2
