traefik:
  rbac:
    enabled: true

  # Enable dashboard - don't keep it publicly open on production environments without appropriate protection (fw, security groups, auth, ip filtering, etc.)
  dashboard:
    enabled: true
  ports:
    traefik:
      expose: true

    websecure:
      tls: {}

  #      # Letsencrypt example with DNSMadeEasy
  #      certResolver: letsencrypt-dnsmadeeasy
  #      domains:
  #        - main: ${DOMAIN}
  #          sans:
  #            - "*.${DOMAIN}"

  # Enable access logs
  logs:
    general:
      # Format is required due to a bug in the helm chart for the specific version K3s is using at the time being (2023-09).
      format: common
      # Set the debug level to debug temporarily to troubleshoot
      #level: DEBUG
    access:
      enabled: true

  service:
    annotations:
      # On AWS, create a Network load balancer with IP target groups
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true

      # You must specify three elastic IPs if you are using 3 availability zones and 3 subnets
      #service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-xxx, eipalloc-yyy, eipalloc-zzz

  externalTrafficPolicy: Local

  persistence:
    enabled: false

  ## Use an existing tls cert and set as default, for example when you use cert-manager for certificate management
  #tlsStore:
  #  default:
  #    defaultCertificate:
  #      secretName: wildcard-example-com-tls

  deployment:
    replicas: 3

  #  # Letsencrypt permissions
  #  initContainers:
  #    - name: volume-permissions
  #      image: busybox:latest
  #      command: [ "sh", "-c", "chmod -Rv 600 /data/* || true" ]
  #      volumeMounts:
  #        - name: data
  #          mountPath: /data
  #
  # Letsencrypt example with DNSMadeEasy
  #certResolvers:
  #  letsencrypt-dnsmadeeasy:
  #    #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  #    dnsChallenge:
  #      provider: dnsmadeeasy
  #      delaybeforecheck: 60
  #    storage: /data/letsencrypt-dnsmadeeasy.json
  #env:
  #  - name: DNSMADEEASY_API_KEY
  #    valueFrom:
  #      secretKeyRef:
  #        name: dnsmadeeasy
  #        key: apiKey
  #  - name: DNSMADEEASY_API_SECRET
  #    valueFrom:
  #      secretKeyRef:
  #        name: dnsmadeeasy
  #        key: apiSecret
