{{- $stores := (index .Values "external-secrets-stores") | default dict -}}
{{- range $name, $store := $stores }}
{{- if (dig "enabled" true $store) }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
  {{- $subchartContext := set (deepCopy $) "Values" (index $.Values "external-secrets") }}
  labels:
    {{- include "external-secrets.labels" $subchartContext | nindent 4 }}
  {{- with (index $.Values "external-secrets").commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{ dig "provider" $name $store }}:
      {{- omit $store "enabled" "provider" | toYaml | nindent 6 }}
---
{{- end }}
{{- end }}