registry:
  proxies:
    - name: docker
      remoteUrl: https://registry-1.docker.io
      username: ""
      password: ""

      # Define the authentication of clients connecting to this new proxy registry
      # Allowed values: transparent, htpasswd, credentials, none
      #
      # transparent = use the credentials from the registry (default)
      # htpasswd    = specify a htpasswd format in the authHtpasswd property.
      # credentials = use the username and password from the authUsername and authPassword properties
      # none        = no authentication
      #
      auth: transparent
      # authUsername: ""
      # authPassword: ""
      # To generate a htpasswd formatted string, use:   docker run --entrypoint htpasswd httpd:2 -Bbn username password
      # authHtpasswd: ""

      # Optional, if you want the registry to be ignored when rewriting the image references
      ignoreRewriteForRegistryPod: true

    # - name: ghcr
    #   remoteUrl: https://ghcr.io
    #   auth: transparent
    # Warning: ECR is not compatible with official specs, registry v2 and v3.0.0 does not work with it. See: https://github.com/distribution/distribution/issues/4383
    # - name: ecr
    #   remoteUrl: https://public.ecr.aws
    #   auth: transparent

  # Allowed values: filesystem, s3
  storage: filesystem
  s3:
    region: eu-north-1
    bucket:
    # Optional, typically only needed for S3 compatible storage services (Minio, etc).
    # regionEndpoint:
    # accessKey:
    # secretKey:

  # Generate if you use more than 1 replica, with:    openssl rand -base64 32 | head -c 32 | base64
  secret: ""

  noRewritePodLabels:
    goharbor.io/harbor-container-webhook-disable: "true"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn:

imagePullSecrets: []
replicaCount: 2
image:
  #repository: public.ecr.aws/docker/library/registry
  repository: registry
resources: {}

microservice:
  renderTemplates: false

datadog:
  enabled: true

probes:
  livenessPath: /
  readinessPath: /

priorityClassName: system-cluster-critical

securityContext:
  seLinuxOptions: {}
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

podSecurityContext:
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1000

service:
  port: 5000

deployment:
  command:
    - /bin/registry
    - serve
    - /etc/docker/registry/config.yml

#scheduler:
#  minZones: 2

#affinity:
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchLabels:
#            app.kubernetes.io/name: '{{ template "microservice.name" . }}'
#            app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Release.Namespace }}'
#        topologyKey: kubernetes.io/hostname
#        # Requires feature gate: MatchLabelKeysInPodAffinity
#        #matchLabelKeys:
#        #  - pod-template-hash

cronjobs:
  - name: gc
    schedule: "0 2 * * *"
    command: "/bin/registry garbage-collect --delete-untagged=true /etc/docker/registry/config.yml"
    suspend: false

env:
  OTEL_SDK_DISABLED: true
  OTEL_TRACES_EXPORTER: none
  REGISTRY_LOG_LEVEL: info

files:
  /etc/docker/registry/config.yml:
    content: |
      version: 0.1
      log:
        accesslog:
          disabled: false
        level: info
        formatter: text
        fields:
          service: registry
          environment: production
      storage:
        tag:
          concurrencylimit: 8
        cache:
          blobdescriptor: inmemory
          blobdescriptorsize: 10000
        delete:
          enabled: true
        redirect:
          disable: false
      http:
        addr: :5000
        prefix: /
        relativeurls: false
        draintimeout: 60s
        headers:
          X-Content-Type-Options: [nosniff]
        debug:
          addr: :5001
          prometheus:
            enabled: false
            path: /metrics
        http2:
          disabled: false
        h2c:
          enabled: false
      health:
        storagedriver:
          enabled: true
          interval: 10s
          threshold: 3