{{- $ingressroute := .Values -}}
{{- if and $ingressroute.enabled $ingressroute.tls.enabled $ingressroute.tls.forceHttps }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-redirect-https
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
