{{- $ingressroute := .Values -}}
{{- if and $ingressroute.enabled $ingressroute.responseHeaderMicroservice }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-header-x-microservice
  labels:
    {{- include "microservice.labels" (dict "context" $) | nindent 4 }}
spec:
  headers:
    customResponseHeaders:
      X-Microservice: "{{ include "microservice.fullname" . }}"
{{- end }}
