apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "docker-image-pull-secret.name" .) .Values.secretName }}
  labels:
    {{- include "docker-image-pull-secret.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ include "docker-image-pull-secret.dockerconfigjson" . | quote }}
