apiVersion: v2
name: kubecost
description: A Helm chart for kubecost

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: cost-analyzer
    alias: kubecost
    version: 1.106.0
    repository: oci://public.ecr.aws/kubecost
