host: localhost
username: kubecost
password: <password>

kubecost:
  global:
    additionalLabels:
      tags.datadoghq.com/service: kubecost
    grafana:
      enabled: false
      proxy: false

  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend

  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model

  kubecostMetrics:
    emitPodAnnotations: true
    emitNamespaceAnnotations: true

  prometheus:
    # Disable if you already have kube-state-metrics running in your cluster
    kubeStateMetrics:
      enabled: false

    # Disable both if you already have kube-state-metrics running in your cluster
    #serviceAccounts:
    #  nodeExporter:
    #    create: false
    #nodeExporter:
    #  enabled: false

    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
    nodeExporter:
      tolerations:
        - operator: 'Exists'
      # Do not deploy node-exporter to Fargate nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate

    configmapReload:
      prometheus:
        image:
          repository: public.ecr.aws/bitnami/configmap-reload
          tag: 0.11.1

  reporting:
    productAnalytics: false
