apiVersion: v2
name: zitadel
description: A Helm chart for Zitadel

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: ingressroute
    version: 0.2.x
    repository: file://../ingressroute
    condition: ingressroute.enabled
  - name: zitadel
    version: 7.6.1
    repository: https://charts.zitadel.com
