
karpenter:
  settings:
    # The EKS cluster name
    clusterName:
    # The public EKS Cluster https endpoint
    clusterEndpoint:
    # The Karpenter SQS queue name
    interruptionQueueName:
  serviceAccount:
    # Override the name, as terraform will usually set the irsa to only allow 'karpenter:karpenter' in the trust policy.
    name: karpenter
    annotations:
      # Karpenter IAM role for service account (IRSA)
      eks.amazonaws.com/role-arn:

nodeClass:
  role:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        iops: 3000
        throughput: 125
        deleteOnTermination: true

nodePool:
  # EC2 instances are named containing the provisioner name
  name: default

  # Karpenter works to actively reduce cluster cost by identifying when:
  # - Nodes can be removed as their workloads will run on other nodes in the cluster.
  # - Nodes can be replaced with cheaper variants due to a change in the workloads.
  consolidationPolicy: WhenUnderutilized

  # Wait a number of seconds after a node has no provisioned pods running before Karpenter requests to delete the node.
  # Ignored if consolidationPolicy is set.
  consolidateAfter: 2m
  #ttlSecondsAfterEmpty: 30

  # Define a lifetime on the provisioned nodes, to automatically force recreation with newer up-to-date AMIs with
  # security updates and latest versions installed. Including allowing new Kubernetes versions to be rolled out to
  # nodes automatically. Defaults to 720h if not defined.
  expireAfter: 336h # 14 days = 14 * 24 Hours

  # Specify requirements constraints
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["c", "m", "r"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
