apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-analyzer.fullname" . }}-traefik-auth
  labels:
    {{- include "kubecost.chartLabels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "cost-analyzer.fullname" . }}
  labels:
    {{- include "kubecost.chartLabels" . | nindent 4 }}
spec:
  basicAuth:
    realm: {{ include "cost-analyzer.fullname" . }}
    secret: {{ include "cost-analyzer.fullname" . }}-traefik-auth
  stripPrefix:
    prefixes:
      - "/kubecost"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cost-analyzer.fullname" . }}
  labels:
    {{- include "kubecost.chartLabels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`) && PathPrefix(`/kubecost`)
      services:
        - name: {{ include "cost-analyzer.serviceName" . }}
          port: {{ .Values.kubecost.service.targetPort }}
      middlewares:
        - name: {{ include "cost-analyzer.fullname" . }}
  tls: {}
