{{- if .Values.externalNames }}
{{- range .Values.externalNames }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "external-name.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .externalName }}
  {{- with .ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
