{{- $subchartContext := set (deepCopy $) "Values" .Values.coredns }}
{{- if and .Values.coredns.deployment.enabled .Values.coredns.rbac.create .Values.coredns.rbac.extraRules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "coredns.clusterRoleName" $subchartContext }}-extra
  labels: {{- include "coredns.labels" $subchartContext | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
{{- end }}
---
{{- if and .Values.coredns.deployment.enabled .Values.coredns.rbac.create .Values.coredns.rbac.extraRules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "coredns.clusterRoleName" $subchartContext }}-extra
  labels: {{- include "coredns.labels" $subchartContext | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "coredns.serviceAccountName" $subchartContext }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "coredns.clusterRoleName" $subchartContext }}-extra
{{- end }}
