metrics-server:
  replicas: 2
  podLabels:
    tags.datadoghq.com/service: metrics-server
  serviceAccount:
    create: true
    name: metrics-server
  #args:
  #  - --kubelet-insecure-tls

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

  nodeSelector: {}
