{{/* Dynamic computed values helper */}}
{{- define "computedIngressroute" -}}
ingressroute:
  routes:
  {{- range $proxy := .Values.registry.proxies }}
  {{- $mergedValues := mergeOverwrite (deepCopy $.Values) (dict "nameOverride" (printf "docker-registry-%s" $proxy.name)) }}
  {{- $context := set (deepCopy $) "Values" $mergedValues }}
  {{- $fullName := include "microservice.fullname" $context }}
    - path: "/{{ $proxy.name }}"
      serviceName: {{ $fullName }}
      rewrite:
        regex: "^/{{ $proxy.name }}/(.*)"
        replacement: "/v2/$1"
  {{- end }}
{{- end }}

{{- $dynamicValues := fromYaml (include "computedIngressroute" .) }}
{{- $mergedValues := mergeOverwrite (deepCopy $.Values.microservice) $dynamicValues $.Values }}
{{- $context := set (deepCopy $) "Values" $mergedValues }}
{{- include "microservice.tpl.ingressroute" $context }}
