{{/* Dynamic computed values helper */}}
{{- define "computedIngressroute" -}}
ingressroute:
  responseHeaderMicroservice: true
  routes:
  {{- range $proxy := .Values.registry.proxies }}
  {{- $mergedValues := mergeOverwrite (deepCopy $.Values) (dict "nameOverride" (printf "docker-registry-%s" $proxy.name)) }}
  {{- $context := set (deepCopy $) "Values" $mergedValues }}
  {{- $fullName := include "microservice.fullname" $context }}
    {{- if contains $proxy.remoteUrl "docker.io" }}
    - path: "/v2/{{ $proxy.name }}/[^/]+$"
      serviceName: {{ $fullName }}
      rewrite:
        regex: "^/v2/{{ $proxy.name }}/(.*)"
        replacement: "/v2/library/$1"
    {{- end }}
    - path: "/v2/{{ $proxy.name }}/"
      serviceName: {{ $fullName }}
      rewrite:
        regex: "^/v2/{{ $proxy.name }}/(.*)"
        replacement: "/v2/$1"
  {{- end }}
{{- end }}

{{- $dynamicValues := fromYaml (include "computedIngressroute" .) }}
{{- $mergedValues := mergeOverwrite (deepCopy $.Values.microservice) $dynamicValues $.Values }}
{{- $context := set (deepCopy $) "Values" $mergedValues }}
{{- include "microservice.tpl.ingressroute" $context }}
---
{{- include "microservice.tpl.ingressroute.header-microservice" $context }}
---
{{- include "microservice.tpl.ingressroute.redirect-https" $context }}
