microservice:
  replicaCount: 3

  nameOverride: inflate

  image:
    repository: registry.k8s.io/pause
    tag: "3.10"

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  datadog:
    enabled: true

  # Disable everything not required
  imagePullSecrets: []
  serviceAccount:
    create: false
  service:
    enabled: false
  ingressroute:
    enabled: false
  probes:
    livenessPath:
    readinessPath:

  # Priority class value to use for the pods
  priorityClassValue: -1

  # Define some scheduling constraints
  scheduler:
    minZones: 3

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: '{{ template "microservice.name" . }}'
              app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Release.Namespace }}'
          topologyKey: kubernetes.io/hostname
          # Requires feature gate: MatchLabelKeysInPodAffinity
          #matchLabelKeys:
          #  - pod-template-hash

  # Define the amount of resources we will have over-provisioned, to allow quick pod preemption when there is not enough nodes
  resources:
    requests:
      cpu: 1
      memory: 2Gi
