datadog-operator:
  enabled: true
  installCRDs: true

  # Intake site
  site: datadoghq.eu

  # Datadog credentials secret name
  appKeyExistingSecret: datadog-secret
  apiKeyExistingSecret: datadog-secret

  watchNamespaces: []

secrets:
  secrets:
    # Your DataDog credentials - Application Key & API Key
    # Note: If you update these, you will need to restart the deployments, as the secret is not automatically reloaded.
    datadog-secret:
      # Generate an Application Key here: https://app.datadoghq.eu/organization-settings/application-keys
      app-key:
      # Generate an API Key here: https://app.datadoghq.eu/organization-settings/api-keys
      api-key:

datadogAgent:
  clusterName:
  site: datadoghq.eu
  global: {}
  override: {}
  features:
    #admissionController:
    #  enabled: true
    apm:
      enabled: true
    #clusterChecks:
    #  enabled: true
    #cspm:
    #  enabled: false
    #cws:
    #  enabled: false
    #ebpfCheck:
    #  enabled: false
    #externalMetricsServer:
    #  enabled: false
    #kubeStateMetricsCore:
    #  enabled: true
    #liveContainerCollection:
    #  enabled: true
    #liveProcessCollection:
    #  enabled: false
    logCollection:
      enabled: true
    #npm:
    #  enabled: false
    #oomKill:
    #  enabled: false
    #orchestratorExplorer:
    #  enabled: true
    #prometheusScrape:
    #  enabled: false
    #tcpQueueLength:
    #  enabled: false
    #usm:
    #  enabled: false

