{{- $random := include "helpers.random-string" . -}}
# This secret lives with the ApplicationSet controller and is referenced from the plugin ConfigMap.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-plugin-generator.fullname" . }}
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    {{- include "argocd-plugin-generator.labels" . | nindent 4 }}
stringData:
  token: "{{ $random }}"
---
# This secret lives with the plugin, and is mounted into the plugin container. The ApplicationSet controller must be
# configured with the exact same secret.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-plugin-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-plugin-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: "{{ $random }}"
{{- if and .Values.secrets (gt (len .Values.secrets) 0) -}}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end -}}
