apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-plugin-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-plugin-generator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-plugin-generator.selectorLabels" . | nindent 4 }}
