apiVersion: v2
name: mysql
description: A Helm chart for MySQL

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: mysql
    version: 11.1.17
    repository: oci://registry-1.docker.io/bitnamicharts
