mysql:
  serviceAccount:
    create: true

  architecture: standalone

  auth:
    rootPassword: ""

    createDatabase: true
    database: "temp"

    username: ""
    password: ""

    #existingSecret: mysql-secret

  primary:
    name: master

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
    #  limits:
    #    memory: 512Mi
    #    cpu: 500m

    persistence:
      size: 8Gi

    # Missing support for this in the official helm chart for now
    # persistentVolumeClaimRetentionPolicy:
    #   enabled: true
    #   whenScaled: Retain
    #   whenDeleted: Delete # default is 'Retain'
