# Warning: This chart is primarily used for development, so we don't retain the PVCs by default. RDS is recommended for production.
mysql:
  serviceAccount:
    create: true

  useDeployment: true

  settings:
    allowEmptyRootPassword: false
    skipTZInfo: false
    arguments: []
    #  - --character-set-server=utf8mb4
    #  - --collation-server=utf8mb4_unicode_ci

    rootPassword:
      value: ""

    # Use an existing secret for root credentials instead of static values
    # existingSecret: "mysql-secret"
    # rootPassword:
    #   secretKey: "rootPassword"

  userDatabase:
    # Create a user database on startup
    name:
      value: "temp"
    # Create a user with access to the database
    user:
      value: ""
    password:
      value: ""

    # Use an existing secret for credentials instead of static values
    # existingSecret: "mysql-secret"
    # name:
    #   secretKey: "database"
    # user:
    #   secretKey: "user"
    # password:
    #   secretKey: "password"

  podLabels:
    tags.datadoghq.com/service: mysql

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    # limits:
    #   memory: 512Mi
    #   cpu: 500m

  storage:
    volumeName: "mysql-data"
    size: 8Gi
    keepPVC: false

  networkPolicy: {}
  customScripts: {} # custom scripts to run on startup (.sh, .sql, .sql.gz files that will be placed in /docker-entrypoint-initdb.d)
  extraScripts: "" # configmap that contains custom scripts to run on startup
  #extraConfigs: []


  # Custom my.cnf overrides
  # customConfig: |
  #   [mysqld]
  #   max_connections = 200
