ingressroute:
  enabled: false
  routes:
    - path: /
      host: ollama.[a-z0-9.]+
      priority: 900
      serviceName: ollama
      servicePort: 11434

ollama:
  gpu:
    # -- Enable GPU integration
    enabled: false
    # -- GPU type: 'nvidia' or 'amd'
    type: 'nvidia'
    # -- Number of GPUs to use
    number: 1

  models:
    pull:
      - gemma3
      #- qwen2.5:0.5b

    run:
      - gemma3