{{- if and .Values.files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-files
  labels:
    {{- include "microservice.labels" (dict "context" $) | nindent 4 }}
data:
  {{- range $name, $file := .Values.files }}
  file.{{ $name | replace "/" "_" }}: |
    {{- $file.content | nindent 4 }}
  {{- end }}
{{- end }}
