{{- define "microservice.tpl.cronjob" -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" (dict "context" $ "component" "cronjob") -}}
{{- $serviceAccountName := include "microservice.serviceAccountName" . -}}
{{- range $cronjob := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" $fullName ($cronjob.name | replace " " "-" | lower) | trunc 50 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
    {{- include "helpers.datadog-service-labels" $ | indent 4 }}
  {{- with $cronjob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  timeZone: {{ default "Europe/Stockholm" $cronjob.timeZone }}
  startingDeadlineSeconds: {{ default nil $cronjob.startingDeadlineSeconds }}
  concurrencyPolicy: {{ default "Allow" $cronjob.concurrencyPolicy }}
  suspend: {{ default false $cronjob.suspend }}
  successfulJobsHistoryLimit: {{ default 3 $cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 $cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ ternary $cronjob.backoffLimit 6 (has (kindOf $cronjob.backoffLimit) (list "int" "int64" "float" "float64")) }}
      {{- if $cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ $cronjob.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          annotations:
            karpenter.sh/do-not-disrupt: "true"
            {{- include "microservice.checksumPodAnnotations" $ | indent 12 }}
            {{- with $cronjob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ $serviceAccountName }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds | default 30 }}
          containers:
            - name: {{ $cronjob.name | replace " " "-" | lower }}
              command:
                - /bin/sh
                - -c
                - {{ $cronjob.command }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              {{- if $cronjob.image }}
              image: "{{ $cronjob.image | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) }}"
              {{- else }}
              image: "{{ $.Values.image.repository }}:{{ include "helpers.image-tag" $ }}"
              {{- end }}
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              env:
                {{- include "helpers.list-env-variables" $ | indent 16 }}
              resources:
                {{- include "helpers.wrapResourcesWithQuotes" ($cronjob.resources | default dict) | indent 16 }}
              volumeMounts:
                {{- include "helpers.volume-mounts" (list $ $.Values.pvc "CronJob") | indent 16 }}
                {{- include "helpers.volume-mounts" (list $ $cronjob.pvc "CronJob" ($cronjob.name | replace " " "-" | lower)) | indent 16 }}
                {{- include "helpers.volume-mounts-files" (list $ $.Values.files "CronJob") | indent 16 }}
            {{- range $cronjob.sidecars }}
            {{- $sidecar := .}}
            {{- toYaml (list (omit $sidecar "mounts")) | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) | nindent 12 }}
            {{- if $sidecar.mounts }}
              volumeMounts:
                {{- include "helpers.volume-mounts" (list $ $.Values.pvc "CronJob") | indent 16 }}
                {{- include "helpers.volume-mounts-files" (list $ $.Values.files "CronJob") | indent 16 }}
            {{- end }}
            {{- end }}
          volumes:
            {{- include "helpers.volumes" (list $ $.Values.pvc "CronJob") | indent 12 }}
            {{- include "helpers.volumes" (list $ $cronjob.pvc "CronJob" ($cronjob.name | replace " " "-" | lower)) | indent 12 }}
            {{- include "helpers.volumes-files" (list $ $.Values.files "CronJob") | indent 12 }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $.Values.tolerations $.Values.nodeSelector }}
          tolerations:
            {{- include "microservice.tolerations" $ | nindent 12 }}
          {{- end }}
          {{- with $.Values.hostAliases }}
          hostAliases:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          enableServiceLinks: false
{{- end }}
{{- end }}
