{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" . -}}
{{- $serviceAccountName := include "microservice.serviceAccountName" . -}}
{{- range $cronjob := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" $fullName ($cronjob.name | replace " " "-" | lower) | trunc 52 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  timeZone: {{ default "Europe/Stockholm" $cronjob.timeZone }}
  startingDeadlineSeconds: {{ default nil $cronjob.startingDeadlineSeconds }}
  concurrencyPolicy: {{ default "Allow" $cronjob.concurrencyPolicy }}
  suspend: {{ default false $cronjob.suspend }}
  successfulJobsHistoryLimit: {{ default 3 $cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 $cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ default 6 $cronjob.backoffLimit }}
      {{- if $cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ $cronjob.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          annotations:
            {{- include "microservice.checksumPodAnnotations" $ | indent 12 }}
        spec:
          restartPolicy: OnFailure
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ $serviceAccountName }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds | default 30 }}
          containers:
            - name: {{ $cronjob.name | replace " " "-" | lower }}
              command:
                - /bin/sh
                - -c
                - {{ $cronjob.command }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              {{- if $cronjob.image }}
              image: "{{ $cronjob.image | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) }}"
              {{- else }}
              image: "{{ $.Values.image.repository }}:{{ include "helpers.image-tag" $ }}"
              {{- end }}
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              env:
                {{- include "helpers.list-env-variables" $ | indent 16 }}
              resources:
                {{- include "helpers.wrapResourcesWithQuotes" ($cronjob.resources | default dict) | indent 16 }}
              {{- with $.Values.pvc }}
              volumeMounts:
                {{- include "helpers.volume-mounts" (list $ . "CronJob") | indent 16 }}
              {{- end }}
          {{- with $.Values.pvc }}
          volumes:
            {{- include "helpers.volumes" (list $ . "CronJob") | indent 12 }}
          {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
