{{- if and .Values.deployment (dig "enabled" true .Values.deployment) }}
{{- $fullName := include "microservice.fullname" . -}}
apiVersion: apps/v1
kind: {{ .Values.deployment.kind | default "Deployment" }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  {{- if and .Values.strategy .Values.strategy.type (eq .Values.deployment.kind "Deployment") }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if and .Values.strategy.rollingUpdate (eq .Values.strategy.type "RollingUpdate") }}
    rollingUpdate:
      {{- .Values.strategy.rollingUpdate | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.deployment.kind "StatefulSet" }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  podManagementPolicy: {{ .Values.deployment.statefulSet.podManagementPolicy | default "Parallel" }}
  UpdateStrategy:
    type: RollingUpdate
    {{- if and (eq .Values.deployment.statefulSet.updateStrategy.type "RollingUpdate") .Values.deployment.statefulSet.updateStrategy.rollingUpdate }}
    rollingUpdate:
      {{- toYaml .Values.deployment.statefulSet.updateStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  volumeClaimTemplates:
    {{- $global := .Values.global -}}
    {{- range $pvcName, $pvc := .Values.pvc }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ $pvcName }}
        annotations:
          {{- if $pvc.volumeType }}
          ebs.csi.aws.com/volumeType: {{ $pvc.volumeType | quote }}
          {{- end }}
          {{- if $pvc.iops }}
          ebs.csi.aws.com/iops: {{ $pvc.iops | quote }}
          {{- end }}
          {{- if $pvc.throughput }}
          ebs.csi.aws.com/throughput: {{ $pvc.throughput | quote }}
          {{- end }}
      spec:
        accessModes:
          {{- if $pvc.accessMode }}
          - {{ $pvc.accessMode }}
          {{- else if contains "efs" ($pvc.storageClass | default "") }}
          - ReadWriteMany
          {{- else }}
          - ReadWriteOnce
          {{- end }}
        resources:
          requests:
            {{- if contains "efs" ($pvc.storageClass | default "") }}
            storage: 1Mi
            {{- else }}
            storage: {{ $pvc.size }}
            {{- end }}
        {{- include "helpers.storage-class" (dict "persistence" $pvc "global" $global) | nindent 2 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "microservice.checksumPodAnnotations" . | indent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- range . }}
        {{- toYaml (list .) | nindent 8 }}
          env:
            {{- include "helpers.list-env-variables" $ | indent 12 }}
          {{- with $.Values.pvc }}
          volumeMounts:
            {{- include "helpers.volume-mounts" (list $ . $.Values.deployment.kind) | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $fullName | default .Chart.Name }}
          {{- if .Values.deployment.debug }}
          command: ["/bin/sh", "-c", "sleep infinity"]
          {{- else }}
          {{- with .Values.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "helpers.image-tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" . | indent 12 }}
          ports:
            {{- include "helpers.ports" (list .Values.service "primary") | indent 12 }}
            {{- range $extra := .Values.service.extraPorts }}
            {{- include "helpers.ports" (list $extra "primary") | indent 12 }}
            {{- end }}
          {{- if and .Values.service.enabled .Values.probes .Values.probes.livenessPath (not .Values.deployment.debug) }}
          livenessProbe:
            httpGet:
              path: {{ eq .Values.probes.livenessPath "/" | ternary "" .Values.probes.livenessPath }}
              port: http
          {{- end }}
          {{- if and .Values.service.enabled .Values.probes .Values.probes.readinessPath (not .Values.deployment.debug) }}
          readinessProbe:
            httpGet:
              path: {{ eq .Values.probes.readinessPath "/" | ternary "" .Values.probes.readinessPath }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.pvc }}
            {{- include "helpers.volume-mounts" (list $ . $.Values.deployment.kind) | indent 12 }}
            {{- end }}
            {{- range $name, $val := .Values.files }}
            - name: configmap-files-volume
              mountPath: {{ $name | quote }}
              subPath: "file.{{ $name | replace "/" "_" }}"
              readOnly: true
            {{- end }}
        {{- range .Values.deployment.sidecars }}
        {{- $sidecar := .}}
        {{- toYaml (list (omit $sidecar "mounts")) | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) | nindent 8 }}
          ports:
            {{- include "helpers.ports" (list $.Values.service .name) | indent 12 }}
            {{- range $extra := $.Values.service.extraPorts }}
            {{- include "helpers.ports" (list $extra $sidecar.name) | indent 12 }}
            {{- end }}
          {{- if $sidecar.mounts }}
          volumeMounts:
            {{- with $.Values.pvc }}
            {{- include "helpers.volume-mounts" (list $ . $.Values.deployment.kind) | indent 12 }}
            {{- end }}
          {{- end }}
        {{- end }}
      volumes:
        {{- if eq .Values.deployment.kind "Deployment" }}
        {{- with .Values.pvc }}
        {{- include "helpers.volumes" (list $ . $.Values.deployment.kind) | indent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.files }}
        - name: configmap-files-volume
          configMap:
            name: {{ include "microservice.fullname" . }}-files
            defaultMode: 0644
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity .Values.scheduler.sameHost }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.scheduler.sameHost }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.topologySpreadConstraints .Values.scheduler.minZones }}
      topologySpreadConstraints:
        {{- with .Values.topologySpreadConstraints }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.scheduler.minZones }}
        - maxSkew: 1
          minDomains: {{ .Values.scheduler.minZones }}
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
          matchLabelKeys:
            - pod-template-hash # Makes it unique per ReplicaSet (does not work for StatefulSets)
        {{- end }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
