{{- if and .Values.deployment (dig "enabled" true .Values.deployment) }}
{{- $fullName := include "microservice.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  {{- if and .Values.strategy .Values.strategy.type }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if and .Values.strategy.rollingUpdate (eq .Values.strategy.type "RollingUpdate") }}
    rollingUpdate:
      {{- .Values.strategy.rollingUpdate | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "microservice.checksumPodAnnotations" . | indent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- range . }}
        {{- toYaml (list .) | nindent 8 }}
          env:
            {{- include "helpers.list-env-variables" $ | indent 12 }}
          {{- with $.Values.pvc }}
          volumeMounts:
            {{- include "helpers.volume-mounts" . | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "helpers.image-tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" . | indent 12 }}
          ports:
            {{- include "helpers.ports" (list .Values.service "primary") | indent 12 }}
            {{- range $extra := .Values.service.extraPorts }}
            {{- include "helpers.ports" (list $extra "primary") | indent 12 }}
            {{- end }}
          {{- if and .Values.service.enabled .Values.probes .Values.probes.livenessPath }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
          {{- end }}
          {{- if and .Values.service.enabled .Values.probes .Values.probes.readinessPath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.pvc }}
            {{- include "helpers.volume-mounts" . | indent 12 }}
            {{- end }}
            {{- range $name, $val := .Values.files }}
            - name: configmap-files-volume
              mountPath: {{ $name | quote }}
              subPath: "file.{{ $name | replace "/" "_" }}"
              readOnly: true
            {{- end }}
        {{- range .Values.deployment.sidecars }}
        {{- $sidecar := .}}
        {{- toYaml (list $sidecar) | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) | nindent 8 }}
          ports:
            {{- include "helpers.ports" (list $.Values.service .name) | indent 12 }}
            {{- range $extra := $.Values.service.extraPorts }}
            {{- include "helpers.ports" (list $extra $sidecar.name) | indent 12 }}
            {{- end }}
        {{- end }}
      volumes:
        {{- with .Values.pvc }}
        {{- include "helpers.volumes" (list $ .) | indent 8 }}
        {{- end }}
        {{- if .Values.files }}
        - name: configmap-files-volume
          configMap:
            name: {{ include "microservice.fullname" . }}-files
            defaultMode: 0644
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
