{{- define "microservice.tpl.external-secret" -}}
{{- range $storeName, $store := .Values.externalSecrets }}
{{- if (dig "enabled" true $store) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" $ }}-{{ $storeName }}
  labels:
    {{- include "microservice.labels" (dict "context" $ "component" "app") | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $store.kind | default "ClusterSecretStore" }}
  refreshInterval: {{ $store.refreshInterval | default "1h" }}
  target:
    name: {{ $store.secretName | default (printf "%s-%s" (include "microservice.fullname" $) $storeName) }}
    creationPolicy: Owner
  data:
    {{- range $key, $secretRef := $store.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        {{- $parts := splitList "@" (printf "%v" $secretRef) }}
        key: {{ index $parts 0 }}
        {{- if gt (len $parts) 1 }}
        property: {{ index $parts 1 }}
        {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
