{{- $ingressroute := .Values.ingressroute -}}
{{- if $ingressroute.enabled -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" . -}}
{{- $svcPort := dig "port" 80 (default (dict) .Values.service) -}}
{{- $svcName := $fullName -}}
{{/*
StripPrefix middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if .stripPrefix }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-strip
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- if regexMatch "[+*()\\[\\]{}]" .stripPrefix }}
  stripPrefixRegex:
    regex:
      - {{ .stripPrefix | quote }}
  {{- else }}
  stripPrefix:
    prefixes:
      - {{ .stripPrefix | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{/*
Rewrite middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if and .rewrite .rewrite.regex .rewrite.replacement }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-rewrite
  labels:
    {{- $labels | nindent 4 }}
spec:
  replacePathRegex:
    regex: {{ .rewrite.regex }}
    replacement: {{ .rewrite.replacement }}
---
{{- end }}
{{- end }}
{{/*
Rate Limit middleware (and real-ip-header sometimes)
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if and .rateLimit .rateLimit.average }}
{{- if and (not .rateLimit.ipStrategy) (not .rateLimit.requestHeaderName) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-header-x-real-ip
  labels:
    {{- $labels | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Real-IP: "{client.ip}"
    customResponseHeaders:
      X-Real-IP: "{client.ip}"
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-rate-limit
  labels:
    {{- $labels | nindent 4 }}
spec:
  rateLimit:
    average: {{ .rateLimit.average | default 0 }}
    burst: {{ .rateLimit.burst | default 1 }}
    period: {{ .rateLimit.period | default "1m" | quote }}
    sourceCriterion:
      {{- with .rateLimit.ipStrategy }}
      ipStrategy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .rateLimit.requestHeaderName }}
      requestHeaderName: {{ .rateLimit.requestHeaderName | quote }}
      {{- else if .rateLimit.ipStrategy }}
      requestHeaderName: "X-Forwarded-For"
      {{- else }}
      requestHeaderName: "X-Real-IP"
      {{- end }}
---
{{- end }}
{{- end }}
{{/*
Redirect middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if and .redirect .redirect.regex .redirect.replacement }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-redirect
  labels:
    {{- $labels | nindent 4 }}
spec:
  redirectRegex:
    regex: {{ .redirect.regex }}
    replacement: {{ .redirect.replacement }}
---
{{- end }}
{{- end }}
{{/*
ForwardAuth middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if and .forwardAuth .forwardAuth.address }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-forward-auth
  labels:
    {{- $labels | nindent 4 }}
spec:
  forwardAuth:
    address: {{ .forwardAuth.address | quote }}
    {{- toYaml (omit .forwardAuth "address") | nindent 4 }}
---
{{- end }}
{{- end }}
{{/*
Headers middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if and .headers (or .headers.response .headers.request) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-headers
  labels:
    {{- $labels | nindent 4 }}
spec:
  headers:
    {{- with .headers.request }}
    customRequestHeaders:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .headers.response }}
    customResponseHeaders:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (omit .headers "request" "response") }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}
{{/*
Custom middleware
*/}}
{{- range $index, $route := $ingressroute.routes }}
{{- if .middlewares }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-route{{ $index }}-custom
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml .middlewares | nindent 2 }}
---
{{- end }}
{{- end }}
{{/*
IngressRoute
*/}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  entryPoints:
    {{- if $ingressroute.tls.enabled }}
    - websecure
    {{- end }}
    - web
  routes:
    {{- range $index, $route := $ingressroute.routes }}
    {{- $host := $ingressroute.overrideHost | default .host }}
    - kind: Rule
      priority: {{ .priority | default 0 }}
      {{- if and $host (regexMatch "[+*()\\[\\]{}]" $host) }}
      match: HostRegexp(`{{ $host | replace "," "`,`" }}`) && PathPrefix(`{{ .path }}`)
      {{- else if $host }}
      match: Host(`{{ $host | replace "," "`,`" }}`) && PathPrefix(`{{ .path }}`)
      {{- else }}
      match: PathPrefix(`{{ .path }}`)
      {{- end }}
      services:
        - name: {{ .serviceName | default $svcName }}
          port: {{ .servicePort | default $svcPort }}
          nativeLB: {{ .nativeLB | default false }}
      middlewares:
        {{- if and $ingressroute.tls.enabled $ingressroute.tls.forceHttps }}
        - name: {{ $fullName }}-redirect-https
        {{- end }}
        {{- if $ingressroute.responseHeaderMicroservice }}
        - name: {{ $fullName }}-header-x-microservice
        {{- end }}
        {{- if .rateLimit }}
        {{- if and (not .rateLimit.ipStrategy) (not .rateLimit.requestHeaderName) }}
        - name: {{ $fullName }}-route{{ $index }}-header-x-real-ip
        {{- end }}
        - name: {{ $fullName }}-route{{ $index }}-rate-limit
        {{- end }}
        {{- if .forwardAuth }}
        - name: {{ $fullName }}-route{{ $index }}-forward-auth
        {{- end }}
        {{- if .headers }}
        - name: {{ $fullName }}-route{{ $index }}-headers
        {{- end }}
        {{- if .rewrite }}
        - name: {{ $fullName }}-route{{ $index }}-rewrite
        {{- end }}
        {{- if .redirect }}
        - name: {{ $fullName }}-route{{ $index }}-redirect
        {{- end }}
        {{- if .stripPrefix }}
        - name: {{ $fullName }}-route{{ $index }}-strip
        {{- end }}
        {{- if .middlewares }}
        - name: {{ $fullName }}-route{{ $index }}-custom
        {{- end }}
    {{- end }}
  {{- if $ingressroute.tls.enabled }}
  tls:
    {{- if $ingressroute.tls.certResolver }}
    certResolver: {{ $ingressroute.tls.certResolver }}
    {{- end }}
    {{- if $ingressroute.tls.domains }}
    domains:
    {{- range $domain := $ingressroute.tls.domains }}
      - main: {{ $domain.main }}
        {{- with $domain.sans }}
        sans:
          {{- toYaml $domain.sans | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
