{{- define "microservice.tpl.job" -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" (dict "context" $ "component" "job") -}}
{{- $serviceAccountName := include "microservice.serviceAccountName" . -}}
{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" $fullName ($job.name | replace " " "-" | lower) | trunc 53 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
    {{- include "helpers.datadog-service-labels" $ | indent 4 }}
  {{- with $job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (hasKey $job "ttlSecondsAfterFinished") (not (kindIs "invalid" $job.ttlSecondsAfterFinished)) }}
  ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished }}
  {{- end }}
  backoffLimit: {{ ternary $job.backoffLimit 6 (has (kindOf $job.backoffLimit) (list "int" "int64" "float" "float64")) }}
  {{- if $job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
  {{- end }}
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
        {{- with $job.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds | default 30 }}
      containers:
        - name: {{ $job.name | replace " " "-" | lower }}
          command:
            - /bin/sh
            - -c
            - {{ $job.command }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- if $job.image }}
          image: "{{ $job.image | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) }}"
          {{- else }}
          image: "{{ $.Values.image.repository }}:{{ include "helpers.image-tag" $ }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" $ | indent 12 }}
          resources:
            {{- include "helpers.wrapResourcesWithQuotes" ($job.resources | default dict) | indent 12 }}
          volumeMounts:
            {{- include "helpers.volume-mounts" (list $ $.Values.pvc "Job") | indent 12 }}
            {{- include "helpers.volume-mounts" (list $ $job.pvc "Job" ($job.name | replace " " "-" | lower)) | indent 12 }}
            {{- include "helpers.volume-mounts-files" (list $ $.Values.files "Job") | indent 12 }}
      volumes:
        {{- include "helpers.volumes" (list $ $.Values.pvc "Job") | indent 8 }}
        {{- include "helpers.volumes" (list $ $job.pvc "Job" ($job.name | replace " " "-" | lower)) | indent 8 }}
        {{- include "helpers.volumes-files" (list $ $.Values.files "Job") | indent 8 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $.Values.tolerations $.Values.nodeSelector }}
      tolerations:
        {{- include "microservice.tolerations" $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
{{- end }}
{{- end }}
