{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" (dict "context" $ "component" "job") -}}
{{- $serviceAccountName := include "microservice.serviceAccountName" . -}}
{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" $fullName ($job.name | replace " " "-" | lower) | trunc 53 | trimSuffix "-" }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (hasKey $job "ttlSecondsAfterFinished") (not (kindIs "invalid" $job.ttlSecondsAfterFinished)) }}
  ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished }}
  {{- end }}
  backoffLimit: {{ default 6 $job.backoffLimit }}
  {{- if $job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
  {{- end }}
  template:
    spec:
      restartPolicy: OnFailure
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds | default 30 }}
      containers:
        - name: {{ $job.name | replace " " "-" | lower }}
          command:
            - /bin/sh
            - -c
            - {{ $job.command }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- if $job.image }}
          image: "{{ $job.image | replace "${IMAGE_TAG}" (include "helpers.image-tag" $) }}"
          {{- else }}
          image: "{{ $.Values.image.repository }}:{{ include "helpers.image-tag" $ }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" $ | indent 12 }}
          resources:
            {{- include "helpers.wrapResourcesWithQuotes" ($job.resources | default dict) | indent 12 }}
          {{- with $.Values.pvc }}
          volumeMounts:
            {{- include "helpers.volume-mounts" (list $ . "Job") | indent 12 }}
          {{- end }}
      {{- with $.Values.pvc }}
      volumes:
        {{- include "helpers.volumes" (list $ . "Job") | indent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $.Values.tolerations $.Values.nodeSelector }}
      tolerations:
        {{- include "microservice.tolerations" $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
{{- end }}
