{{- define "microservice.tpl.pdb" -}}
{{- if and .Values.pdb .Values.pdb.enabled (or (gt (int .Values.replicaCount) 1) .Values.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" (dict "context" $ "component" "app") | nindent 4 }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end  }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" (dict "context" $ "component" "app") | nindent 6 }}
{{- end }}
{{- end }}
