{{- if .Values.priorityClassValue }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
value: {{ .Values.priorityClassValue | default 0 }}
globalDefault: false
{{- end }}
