{{- define "microservice.tpl.priorityclass" -}}
{{- if and .Values.priorityClassValue }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Namespace }}-{{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" (dict "context" $) | nindent 4 }}
value: {{ .Values.priorityClassValue | default 0 }}
globalDefault: false
{{- end }}
{{- end }}