{{- if .Values.pvc -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" . -}}
{{- $global := .Values.global -}}
{{- range $pvcName, $pvc := .Values.pvc }}
{{- if and (dig "enabled" true $pvc) (not $pvc.existingClaim) (not .hostPath) (not .emptyDir) (not .nfs) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $pvcName }}
  labels:
    {{- $labels | nindent 4 }}
  {{- if or $pvc.volumeType $pvc.iops $pvc.throughput }}
  annotations:
    {{- if $pvc.volumeType }}
    ebs.csi.aws.com/volumeType: {{ $pvc.volumeType | quote }}
    {{- end }}
    {{- if $pvc.iops }}
    ebs.csi.aws.com/iops: {{ $pvc.iops | quote }}
    {{- end }}
    {{- if $pvc.throughput }}
    ebs.csi.aws.com/throughput: {{ $pvc.throughput | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ $pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  {{- include "helpers.storage-class" (dict "persistence" $pvc "global" $global) | nindent 2 }}
{{- printf "\n" }}
{{- end }}
{{- end }}
{{- end }}
