{{- if .Values.pvc -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $labels := include "microservice.labels" . -}}
{{- $global := .Values.global -}}
{{- range $pvcName, $pvc := .Values.pvc }}
{{- if and (dig "enabled" true $pvc) (not $pvc.existingClaim) (not .hostPath) (not .emptyDir) (or (not .nfs) .nfs.mountOptions) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $pvcName }}
  labels:
    {{- $labels | nindent 4 }}
  {{- if or $pvc.volumeType $pvc.iops $pvc.throughput }}
  annotations:
    {{- if $pvc.volumeType }}
    ebs.csi.aws.com/volumeType: {{ $pvc.volumeType | quote }}
    {{- end }}
    {{- if $pvc.iops }}
    ebs.csi.aws.com/iops: {{ $pvc.iops | quote }}
    {{- end }}
    {{- if $pvc.throughput }}
    ebs.csi.aws.com/throughput: {{ $pvc.throughput | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- if $pvc.accessMode }}
    - {{ $pvc.accessMode }}
    {{- else if .nfs }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      {{- if or .nfs (contains "efs" $pvc.storageClass) }}
      storage: 1Mi
      {{- else }}
      storage: {{ $pvc.size }}
      {{- end }}
  {{- if or .nfs .csi }}
  storageClassName: ""
  volumeName: {{ $fullName }}-{{ $pvcName }}-pv
  {{- else }}
  {{- include "helpers.storage-class" (dict "persistence" $pvc "global" $global) | nindent 2 }}
  {{- end }}
{{- printf "\n" }}
{{- if or .nfs .csi }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-{{ $pvcName }}-pv
  labels:
    {{- $labels | nindent 4 }}
spec:
  accessModes:
    {{- if $pvc.accessMode }}
    - {{ $pvc.accessMode }}
    {{- else if .nfs }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  capacity:
    {{- if or .nfs (contains "efs" $pvc.storageClass) }}
    storage: 1Mi
    {{- else }}
    storage: {{ $pvc.size }}
    {{- end }}
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  {{- if .nfs }}
  mountOptions:
    {{- toYaml .nfs.mountOptions | nindent 4 }}
  nfs:
    {{- toYaml (omit .nfs "mountOptions") | nindent 4 }}
  {{- else if .csi }}
  {{- with .csi.mountOptions }}
  mountOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  csi:
    {{- toYaml (omit .csi "mountOptions") | nindent 4 }}
  {{- end }}
{{- printf "\n" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
