{{- define "microservice.tpl.ingressroute.compress" -}}
{{- $ingressroute := .Values.ingressroute -}}
{{- if and $ingressroute.enabled $ingressroute.compress }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-compress
  labels:
    {{- include "microservice.labels" (dict "context" $) | nindent 4 }}
spec:
  compress:
    defaultEncoding: ""
    encodings:
      - zstd
      - br
      - gzip
    minResponseBodyBytes: 1024
    includedContentTypes:
      - application/javascript
      - application/json
      - application/rss+xml
      - application/wasm
      - application/xhtml+xml
      - application/xml
      - image/svg+xml
      - text/css
      - text/html
      - text/plain
      - text/xml
{{- end }}
{{- end }}
