{{- $ingressroute := .Values.ingressroute -}}
{{- if and $ingressroute.enabled $ingressroute.headers }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-headers
  labels:
    {{- include "microservice.labels" (dict "context" $) | nindent 4 }}
spec:
  headers:
    {{- $headers := $ingressroute.headers }}
    {{- $mapping := dict "response" "customResponseHeaders" "request" "customRequestHeaders" }}
    {{- $renamed := dict }}
    {{- range $old, $new := $mapping }}
      {{- if hasKey $headers $old }}
        {{- $_ := set $renamed $new (index $headers $old) }}
      {{- end }}
    {{- end }}
    {{- $clean := deepCopy $headers }}
    {{- range $old := keys $mapping }}
      {{- $_ := unset $clean $old }}
    {{- end }}
    {{- toYaml (merge $clean $renamed) | nindent 4 }}
{{- end }}
