{{- $labels := include "karpenter.labels" . -}}
{{- range $name, $class := .Values.nodeClass }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  role: {{ default $.Values.nodeClassDefaultRole $class.role | default (printf "KarpenterNodeRole-%s" $.Values.karpenter.settings.clusterName) }}
  amiFamily: {{ $class.amiFamily }}
  tags:
    karpenter.sh/discovery: {{ $.Values.karpenter.settings.clusterName }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $.Values.karpenter.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $.Values.karpenter.settings.clusterName }}
  {{- toYaml (omit $class "role" "amiFamily") | nindent 2 }}
{{- end }}
