{{- $labels := include "karpenter.labels" . -}}
{{- range $provisioner := .Values.provisioners }}
{{- if dig ($provisioner.nodePool) "enabled" true $.Values.nodePool }}
{{- if gt (len (dig ($provisioner.nodePool) "requirements" (list) $.Values.nodePool)) 0 }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $provisioner.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  weight: {{ dig ($provisioner.nodePool) "weight" 1 $.Values.nodePool }}
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ $provisioner.nodeClass }}
      expireAfter: {{ dig ($provisioner.nodePool) "expireAfter" "336h" $.Values.nodePool }}
      terminationGracePeriod: {{ dig ($provisioner.nodePool) "terminationGracePeriod" "48h" $.Values.nodePool }}
      requirements:
        {{- dig ($provisioner.nodePool) "requirements" (list) $.Values.nodePool | toYaml | nindent 8 }}
      {{- if or $provisioner.nodePoolTaint (gt (len (dig ($provisioner.nodePool) "taints" (list) $.Values.nodePool)) 0) }}
      taints:
        {{- if $provisioner.nodePoolTaint }}
        - key: "karpenter.sh/nodepool"
          value: {{ $provisioner.name | quote }}
          effect: {{ $provisioner.nodePoolTaint | quote }}
        {{- end }}
        {{- with dig ($provisioner.nodePool) "taints" (list) $.Values.nodePool }}
        {{- range . }}
        - key: {{ .key | quote }}
          {{- if eq .key "karpenter.sh/nodepool" }}
          value: {{ $provisioner.name | quote }}
          {{- else if .value }}
          value: {{ .value | quote }}
          {{- end }}
          {{- if .effect }}
          effect: {{ .effect | quote }}
          {{- end }}
        {{ end }}
        {{- end }}
      {{- end }}
  limits:
    cpu: {{ dig ($provisioner.nodePool) "limits" "cpu" 0 $.Values.nodePool | quote }}
    memory: {{ dig ($provisioner.nodePool) "limits" "memory" "0Gi" $.Values.nodePool }}
  disruption:
    consolidationPolicy: {{ dig ($provisioner.nodePool) "consolidationPolicy" "WhenEmptyOrUnderutilized" $.Values.nodePool }}
    consolidateAfter: {{ dig ($provisioner.nodePool) "consolidateAfter" "2m" $.Values.nodePool }}
    budgets:
      {{- if (dig ($provisioner.nodePool) "budgets" false $.Values.nodePool) }}
      {{- dig ($provisioner.nodePool) "budgets" false $.Values.nodePool | toYaml | nindent 6 }}
      {{- else }}
      - nodes: "10%"
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
