{{- $labels := include "karpenter.labels" . -}}
{{- range $provisioner := .Values.provisioners }}
{{- if dig ($provisioner.nodePool) "enabled" true $.Values.nodePool }}
{{- if gt (len (dig ($provisioner.nodePool) "requirements" (list) $.Values.nodePool)) 0 }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ $provisioner.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  template:
    spec:
      nodeClassRef:
        name: {{ $provisioner.nodeClass }}
      requirements:
        {{- dig ($provisioner.nodePool) "requirements" (list) $.Values.nodePool | toYaml | nindent 8 }}
  limits:
    cpu: {{ dig ($provisioner.nodePool) "limits" "cpu" 0 $.Values.nodePool | quote }}
    memory: {{ dig ($provisioner.nodePool) "limits" "memory" "0Gi" $.Values.nodePool }}
  disruption:
    consolidationPolicy: {{ dig ($provisioner.nodePool) "consolidationPolicy" "WhenUnderutilized" $.Values.nodePool }}
    {{- if not (dig ($provisioner.nodePool) "consolidationPolicy" false $.Values.nodePool) }}
    consolidateAfter: {{ dig ($provisioner.nodePool) "consolidateAfter" "2m" $.Values.nodePool }}
    {{- end }}
    expireAfter: {{ dig ($provisioner.nodePool) "expireAfter" "336h" $.Values.nodePool }}
  weight: {{ dig ($provisioner.nodePool) "weight" 0 $.Values.nodePool }}
{{- end }}
{{- end }}
{{- end }}
