apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodePool.name }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  role: {{ .Values.nodeClass.role | default (printf "KarpenterNodeRole-%s" .Values.karpenter.settings.clusterName) }}
  amiFamily: {{ .Values.nodeClass.amiFamily }}
  tags:
    karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  {{- toYaml (omit .Values.nodeClass "role" "amiFamily") | nindent 2 }}
