apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Values.provisioner.name }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  requirements:
    {{- toYaml .Values.provisioner.requirements | nindent 4 }}
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: {{ .Values.provisioner.ttlSecondsAfterEmpty }}
  ttlSecondsUntilExpired: {{ .Values.provisioner.ttlSecondsUntilExpired }}
  consolidation:
    enabled: {{ .Values.provisioner.consolidationEnabled }}
  providerRef:
    name: default
