apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

dependencies:
  - name: cert-manager
    version: v1.13.0
    repository: https://charts.jetstack.io
