cert-manager:
  # The chart is a bit buggy with the CRDs installation if the releaseName is provided, lets override the name to avoid issues
  fullnameOverride: cert-manager
  #namespace: cert-manager
  extraArgs:
    - --enable-certificate-owner-ref=true
  installCRDs: true
  serviceAccount:
    create: true
    name: cert-manager
  webhook:
    # Default port is 10250, which is also used for kubelet on Fargate. Changing it to 10260 to avoid conflict.
    securePort: 10260
