cert-manager:
  # The chart is a bit buggy with the CRDs installation if the releaseName is provided, lets override the name to avoid issues
  fullnameOverride: cert-manager
  #namespace: cert-manager
  crds:
    enabled: true
    keep: true
  dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
  dns01RecursiveNameserversOnly: true
  # Whether to set the certificate resource as an owner of secret where the tls certificate is stored.
  # When this flag is enabled, the secret will be automatically removed when the certificate resource is deleted.
  # In other words, if you want automatic deletion/clean-up, set this flag to true. If you want to retain the secret, keep as false.
  enableCertificateOwnerRef: false
  serviceAccount:
    create: true
    name: cert-manager
    annotations:
      eks.amazonaws.com/role-arn:
  securityContext:
    fsGroup: 1001
  podLabels:
    tags.datadoghq.com/service: cert-manager
  webhook:
    # Default port is 10250, which is also used for kubelet on Fargate. Changing it to 10260 to avoid conflict.
    securePort: 10260
