apiVersion: v2
name: redis
description: A Helm chart for Redis

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.2.0

dependencies:
  - name: redis
    version: "2.1.5"
    repository: https://groundhog2k.github.io/helm-charts/
