redis:
  architecture: standalone
  auth:
    enabled: false
    password: ""

  # Override how pvc's are managed throughout the lifecycle of the Stateful Set for the different components of redis
  master:
    podLabels:
      tags.datadoghq.com/service: redis
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete # default is 'Retain'
    persistence:
      enabled: true
  replica:
    podLabels:
      tags.datadoghq.com/service: redis
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete # default is 'Retain'
    persistence:
      enabled: true
  sentinel:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete # default is 'Retain'
    persistence:
      enabled: true
