redis:
  serviceAccount:
    create: true

  useDeploymentWhenNonHA: true

  # Use a high available sentinel architecture instead of a single Redis instance
  haMode:
    enabled: false

  podLabels:
    tags.datadoghq.com/service: redis

  priorityClassName: ""
  nodeSelector: {}
  tolerations: []

  storage:
    volumeName: "redis-data"
    # If no size is set, emptyDir will be used (no persistence).
    requestedSize: 8Gi
    # Keep the dynamically created PVC (only for non-HA mode with option useDeploymentWhenNonHA: true)
    keepPVC: false

  # Resource requests/limits for Redis pods
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    # limits:
    #   memory: 512Mi
    #   cpu: 200m

  ## Additional redis.conf
  redisConfig: |
    #requirepass <password>  # Uncomment and set a password if authentication is needed

  ## Additional sentinel.conf (only when haMode is enabled) - Ensure to configure the auth appropriately.
  sentinelConfig: |
